using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Motor.Generators;

[Generator]
public class ActorActivatorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Ищем все объявления классов, у которых есть хотя бы один атрибут
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax c && c.AttributeLists.Count > 0,
                transform: static (ctx, _) => GetActorClassInfo(ctx))
            .Where(static m => m is not null);

        // 2. Явно приводим поток данных к non-nullable типу перед сборкой в массив
        var nonNullableClasses = classDeclarations.Select(static (item, _) => item!.Value);

        // 3. Собираем отфильтрованные данные в единый массив
        IncrementalValueProvider<ImmutableArray<ActorClassData>> collectedClasses = nonNullableClasses.Collect();

        // 3. Генерируем финальный код фабрики
        context.RegisterSourceOutput(collectedClasses, static (spc, source) => Execute(source, spc));
    }

    private static ActorClassData? GetActorClassInfo(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var model = context.SemanticModel;

        if (model.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol typeSymbol)
            return null;

        // Ищем атрибут ActorRole
        var attribute = typeSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == "RegisterRoleAttribute" || a.AttributeClass?.Name == "RegisterRole");

        if (attribute == null || attribute.ConstructorArguments.Length == 0)
            return null;

        // Достаем строковое значение роли из конструктора атрибута
        string? roleName = attribute.ConstructorArguments[0].Value?.ToString();
        if (string.IsNullOrEmpty(roleName)) return null;

        // Получаем полное имя класса с неймспейсом (например, Graphics.RectangleShape)
        string fullClassName = typeSymbol.ToDisplayString();

        return new ActorClassData(roleName!, fullClassName);
    }

    private static void Execute(ImmutableArray<ActorClassData> classes, SourceProductionContext context)
    {
        if (classes.IsDefaultOrEmpty) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("namespace Motor.Core.Actors;"); // Укажите пространство имен вашего движка
        sb.AppendLine();
        sb.AppendLine("public static partial class ActorActivator");
        sb.AppendLine("{");
        sb.AppendLine("    public static partial Actor Create(string role)");
        sb.AppendLine("    {");
        sb.AppendLine("        return role switch");
        sb.AppendLine("        {");

        // Генерируем строки для каждого найденного класса актора
        foreach (var actor in classes.Distinct())
        {
            sb.AppendLine($"            \"{actor.RoleName}\" => new {actor.FullClassName}(true),");
        }

        sb.AppendLine("            _ => throw new Exception($\"Unknown actor role: {role}\")");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("ActorActivator.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}

// Простая структура для хранения данных между этапами генерации
struct ActorClassData(string roleName, string fullClassName)
{
    public string RoleName = roleName;
    public string FullClassName = fullClassName;
}
