using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Motor.Generators;

[Generator]
public class ModifierActivatorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Ищем все объявления классов, у которых есть хотя бы один атрибут
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax c && c.AttributeLists.Count > 0,
                transform: static (ctx, _) => GetModifierClassInfo(ctx))
            .Where(static m => m is not null);

        // 2. Явно приводим поток данных к non-nullable типу перед сборкой в массив
        var nonNullableClasses = classDeclarations.Select(static (item, _) => item!.Value);

        // 3. Собираем отфильтрованные данные в единый массив
        IncrementalValueProvider<ImmutableArray<ModifierClassData>> collectedClasses = nonNullableClasses.Collect();

        // 3. Генерируем финальный код фабрики
        context.RegisterSourceOutput(collectedClasses, static (spc, source) => Execute(source, spc));
    }

    private static ModifierClassData? GetModifierClassInfo(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var model = context.SemanticModel;

        if (model.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol typeSymbol)
            return null;

        // Ищем атрибут RegisterModifier
        var attribute = typeSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == "RegisterModifierAttribute" || a.AttributeClass?.Name == "RegisterModifier");

        if (attribute == null || attribute.ConstructorArguments.Length == 0)
            return null;

        // Достаем строковое значение роли из конструктора атрибута
        string? roleName = attribute.ConstructorArguments[0].Value?.ToString();
        if (string.IsNullOrEmpty(roleName)) return null;

        var dtoTypeSymbol = attribute.ConstructorArguments[1].Value as INamedTypeSymbol;
        if (dtoTypeSymbol == null) return null;

        // Получаем полное имя класса с неймспейсом (например, Graphics.RectangleShape)
        string fullClassName = typeSymbol.ToDisplayString();
        string fullDtoName = dtoTypeSymbol.ToDisplayString();

        return new ModifierClassData(roleName!, fullClassName, fullDtoName);
    }

    private static void Execute(ImmutableArray<ModifierClassData> classes, SourceProductionContext context)
    {
        if (classes.IsDefaultOrEmpty) return;

        var uniqueClasses = classes
            .GroupBy(static modifier => modifier.Name, StringComparer.Ordinal)
            .Select(static g => g.First())
            .OrderBy(static modifier => modifier.Name, StringComparer.Ordinal)
            .ToArray();

        EmitModifierActivator(uniqueClasses, context);
        EmitModifierDataRegistration(uniqueClasses, context);
    }

    private static void EmitModifierActivator(ModifierClassData[] classes, SourceProductionContext context)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("namespace Motor.Core.Modifiers;");
        sb.AppendLine();
        sb.AppendLine("internal static partial class ModifierActivator");
        sb.AppendLine("{");
        sb.AppendLine("    public static partial ModifierBase Create(string name)");
        sb.AppendLine("    {");
        sb.AppendLine("        return name switch");
        sb.AppendLine("        {");

        foreach (var modifier in classes)
            sb.AppendLine($"            \"{modifier.Name}\" => new {modifier.FullClassName}(),");

        sb.AppendLine("            _ => throw new Exception($\"Unknown modifier name: {name}\")");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("ModifierActivator.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitModifierDataRegistration(ModifierClassData[] classes, SourceProductionContext context)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine("namespace Motor.Core.Modifiers;");
        sb.AppendLine();
        sb.AppendLine("public abstract partial class ModifierBase");
        sb.AppendLine("{");
        foreach (var modifier in classes)
            sb.AppendLine($"    [JsonDerivedType(typeof({modifier.FullDtoName}), \"{modifier.Name}\")]");

        sb.AppendLine("    internal partial record ModifierData { }");
        sb.AppendLine("}");

        context.AddSource("ModifierBase.Serialization.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}

// Простая структура для хранения данных между этапами генерации
struct ModifierClassData(string name, string fullClassName, string fullDtoName)
{
    public string Name = name;
    public string FullClassName = fullClassName;
    public string FullDtoName = fullDtoName;
}
